<?php

const BOT_BASE_DIRECTORY = '/var/vk-bot';
const BOT_LOGS_DIRECTORY = BOT_BASE_DIRECTORY . '/logs';
define('CALLBACK_API_CONFIRMATION_TOKEN', $_ENV('CALLBACK_API_CONFIRMATION_TOKEN'));
define('VK_API_ACCESS_TOKEN', $_ENV('VK_API_ACCESS_TOKEN'));
define('BD_SERVERNAME', $_ENV('BD_SERVERNAME'));
define('BD_DATABASE', $_ENV('BD_DATABASE'));
define('BD_USERNAME', $_ENV('BD_USERNAME'));
define('BD_PASSWORD', $_ENV('BD_PASSWORD'));